name: Trigger auto deployment for api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ matthieug ]
    paths:
    - 'Student/Resources/Challenge 1/content-api/**'
    - '.github/workflows/api-AutoDeployTrigger-e5349415-b7d0-460a-8688-09da1e1c7fbe.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: sncfml.azurecr.io
          username: ${{ secrets.API_REGISTRY_USERNAME }}
          password: ${{ secrets.API_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sncfml.azurecr.io/content-api:${{ github.sha }}
          file: Student/Resources/Challenge 1/api/Dockerfile
          context: Student/Resources/Challenge 1/content-api/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.API_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n api -g ml --server sncfml.azurecr.io --username  ${{ secrets.API_REGISTRY_USERNAME }} --password ${{ secrets.API_REGISTRY_PASSWORD }}
            az containerapp update -n api -g ml --image sncfml.azurecr.io/api:${{ github.sha }}
